Added common implementation of triplet finding and weight updating
acts-project/traccc pull request #219
Opened 2022-08-24 15:37 UTC by guilhermeAlmeida1

Following #212 , a common implementation was now created for the 2 next steps in seed finding.

No significant difference in performance was observed for now, which was expected due to the poor performance of the get_prefix_sum function already observed in #217 #218 .

Sample performance output:
./bin/traccc_seq_example_sycl --detector_file=tml_detector/trackml-detector.csv --digitization_config_file=tml_detector/default-geometric-config-generic.json --input_directory=tml_full/ttbar_mu100/ --run_cpu=0 --events=10

**NEW:**
==> Elpased time ... 
wall time           34.8908   
file reading (cpu)        30.805    
clusterization_time (cpu) 0         
spacepoint_formation_time (cpu) 0         
clusterization_time (sycl) 0.566461  
seeding_time (cpu)        0         
seeding_time (sycl)       3.31363   
tr_par_esti_time (cpu)    0         
tr_par_esti_time (sycl)   0.205617

**OLD:**
wall time           34.6785   
file reading (cpu)        30.5384   
clusterization_time (cpu) 0         
spacepoint_formation_time (cpu) 0         
clusterization_time (sycl) 0.570876  
seeding_time (cpu)        0         
seeding_time (sycl)       3.36168   
tr_par_esti_time (cpu)    0         
tr_par_esti_time (sycl)   0.207476

2022-08-29 15:48 UTC, krasznaa requested changes
Let's start with just these. I'll continue looking tomorrow. :wink:

2022-08-29 15:48 UTC, krasznaa commented on device/common/include/traccc/seeding/device/weight_updating.hpp
> +void update_weights(const std::size_t globalIndex,
The function name is okay like this. Though I would prefer to make it even a bit more explicit, and call it `traccc::device::update_triplet_weights`.

But importantly, make sure that the file names correspond to the function names. At first I thought the function would be called `traccc::device::weight_updating`...

2022-08-29 15:48 UTC, krasznaa commented on device/common/include/traccc/seeding/device/weight_updating.hpp
> +// Project include(s).
Add the common copyright statement to all new files.

Also, add

```c++
#pragma once
```

to all of the header files. (Checking again, you only seem to have forgotten about both of them for this one file. :stuck_out_tongue:)

2022-08-29 15:54 UTC, guilhermeAlmeida1 commented
Ignore this latest push for now, that was just rebasing off of the main branch. I will make the changes requested here tomorrow as well

2022-09-02 08:00 UTC, krasznaa requested changes
Most of them are **very** surface level requests. The only real change is with the `triplet` handling in the weight updating kernel. :wink:

2022-09-02 09:23 UTC, krasznaa requested changes
Still one small correction...

2022-09-02 09:23 UTC, krasznaa commented on device/common/include/traccc/seeding/device/impl/update_triplet_weights.ipp
> +                filter_config.compatSeedWeight;
Ahh... This is not what I had in mind...

Let's use `this_triplet` in this line. Let's just update the weight in the thread-specific variable during the for-loop.

Then, at the very end of the function, after the for-loop, let's just write to the global memory once.

```c++
triplets_per_bin[ps_idx.second].weight = this_triplet.weight;
```

2022-09-02 09:46 UTC, krasznaa approved these changes
Okay, as long as the CI succeeds, and you say that the code works correctly like this, let's go with this version...

2022-09-02 11:23 UTC, merged