Introduce traccc::pair, main branch (2022.09.07.)
acts-project/traccc pull request #229
Opened 2022-09-07 15:42 UTC by krasznaa

Introduced `traccc::pair`, and updated the container code to use it.

Some functions of the [std::pair](https://en.cppreference.com/w/cpp/utility/pair) type are not available in device code, which required us declaring some awkward functions earlier. With the `traccc::pair` type those functions could be deleted.

However I still introduced more new lines of code than how many I managed to delete. :stuck_out_tongue: So I'm curious what everyone thinks about the merit of this PR... (I'll want to make additional updates to the EDM code after this, I just didn't like how `traccc::seed` looked like at the moment...)

2022-09-07 17:09 UTC, beomki-yeo commented
isn't `thrust::pair` usable?

2022-09-07 17:56 UTC, stephenswat requested changes

2022-09-07 17:56 UTC, stephenswat commented on core/include/traccc/utils/impl/pair.ipp
> +    : first(f), second(s) {}
You are missing `std::forward` here.

2022-09-07 17:56 UTC, stephenswat commented on core/include/traccc/utils/impl/pair.ipp
> +    : first(parent.first), second(parent.second) {}
This needs `std::move`.

2022-09-07 17:56 UTC, stephenswat commented on core/include/traccc/utils/impl/pair.ipp
> +    : first(parent.first), second(parent.second) {}
Needs `std::move`.

2022-09-14 14:47 UTC, krasznaa commented
Closing in favour of #231.

2022-09-14 14:47 UTC, closed without merging