File reading small improvement
acts-project/traccc pull request #273
Opened 2022-11-15 16:10 UTC by guilhermeAlmeida1

This additional check reduces computation by only looking for the cell's module if it's not a repeat of the previous one. Elapsed time for file reading time is reduced by ~35%.

2022-11-15 19:34 UTC, beomki-yeo commented
It looks good to me but I don't know why it fails with Kokkos

2022-11-15 19:38 UTC, krasznaa commented
Kokkos is irrelevant there. The failing tests are pure c\+\+ ones. (It's just by chance that this was the first platform on which this test failed.)

Guilherme, I suspect those tests should fail for you locally as well. You'll need to debug tomorrow what's going wrong.

2022-11-16 09:57 UTC, guilhermeAlmeida1 commented
The problem was actually quite simple, but I ended up simplifying this whole PR by just changing to using a reverse iterator which also solves the issue. Also added this functionality to the other csv reading functions. Hopefully this should work now but let's wait for the CI

2022-11-16 12:42 UTC, krasznaa requested changes
I like it! The switch to reverse iterators in the search is very elegant! :smile:

2022-11-16 12:42 UTC, krasznaa commented on io/include/traccc/io/csv.hpp
> +            auto idx = std::distance(headers.begin(), rit.base()) - 1;
This is correct. But you should add just one line of explanation of why the `-1` is necessary. It's actually pretty educational to understand this. (Do you? :wink:)

2022-11-17 08:30 UTC, krasznaa approved these changes
:+1:

2022-11-17 08:30 UTC, merged