Spacepoint binning
acts-project/traccc pull request #277
Opened 2022-11-17 04:06 UTC by Yhatoh

Hi!

I closed the previous PR ( https://github.com/acts-project/traccc/pull/270 ). And in this branch in my fork, i did the changes requested. 

So in the seeding examples, I put the full CPU seeding algorithm and only the spacepoint binning for Kokkos.

Also, I used the format from VS Code to format the code (I think now is correct).

Cheers,
Gabriel

2022-11-17 08:49 UTC, krasznaa requested changes
Some changes are needed, but I don't see anything fundamentally wrong here. Just some small cleanup here and there.

2022-11-17 08:49 UTC, krasznaa commented on device/kokkos/CMakeLists.txt
> +  # CCL code.
You should remove this line.

2022-11-18 09:50 UTC, krasznaa commented
#278 should make this PR build in the CI.

But you still need to fix the formatting of the code. If you have Docker available, the easiest is to do the following:

```
cd traccc/
docker run -it --rm -v $PWD:$PWD -w $PWD --user "$(id -u):$(id -g)" ghcr.io/acts-project/format10:v11
./.github/check_format.sh .
```

And then add all the changes that the [check_format.sh](https://github.com/acts-project/traccc/blob/main/.github/check_format.sh) script makes, to this PR.

2022-11-21 09:15 UTC, krasznaa approved these changes
Okay, let's go ahead with it. So that you can move on to the seed-finding algorithm. :wink:

2022-11-21 09:16 UTC, merged

2022-11-21 10:55 UTC, Yhatoh commented
Thanks!