Ensure synchronisation with async copies
acts-project/traccc pull request #380
Opened 2023-04-14 12:56 UTC by guilhermeAlmeida1

Fixing a small issue which apparently has not manifested itself so far, but could be a source of trouble. When the examples were changed to use asynchronous copies some synchronisation points were missed. I'm not sure whether in the CUDA case that was already not implicitly done.

2023-04-14 13:03 UTC, guilhermeAlmeida1 commented
I took the opportunity to just make the sycl/cuda examples the same. I don't really see any particular reason to keep the synchronous copies in.

2023-04-21 12:01 UTC, krasznaa requested changes
Looks good, just some technical suggestions.

2023-04-21 13:01 UTC, guilhermeAlmeida1 commented on examples/run/cuda/seeding_example_cuda.cpp
> +        stream.synchronize();
Done

2023-04-21 13:31 UTC, krasznaa approved these changes
:+1:

2023-04-21 15:22 UTC, krasznaa approved these changes

2023-04-21 15:27 UTC, merged