build: include tbb as a system library and add compile flag -Wfloat-conversion
acts-project/traccc pull request #622
Opened 2024-06-20 15:07 UTC by fredevb

2024-06-20 16:37 UTC, krasznaa requested changes
Please check what happens with your build after all of this. For instance, you could do:

```
VERBOSE=1 make traccc_tbb_task_example
```

, and see how the TBB include directory/directories appear(s) in the compilation commands. They should **only** appear with `-isystem` for this PR to be successful.

2024-06-20 16:37 UTC, krasznaa commented on cmake/traccc-compiler-options-cpp.cmake
> +   traccc_add_fkag( CMAKE_CXX_FLAGS "-Wfloat-conversion" )
Typo...

2024-06-20 16:37 UTC, krasznaa commented on extern/tbb/CMakeLists.txt
> +unset( _incDirs )
:thinking: TBB is actually a `SHARED` library, not an `INTERFACE` one. (I didn't think about this in the office.) So you'll likely rather need to do:

```suggestion
get_target_property( _incDirs tbb INCLUDE_DIRECTORIES )
target_include_directories( tbb
   SYSTEM PUBLIC ${_incDirs} )
unset( _incDirs )
```

2024-06-20 16:39 UTC, krasznaa commented
And I very much agree with @stephenswat. You should write a little more details into the PRs. For instance in this case you could've documented that you wrote the code based on the setup for Eigen. :thinking:

2024-06-21 11:19 UTC, stephenswat commented on extern/tbb/CMakeLists.txt
> +unset( _incDirs )
This needs to go _after_ the call to `FetchContent`.

2024-06-21 16:45 UTC, closed without merging