Add Acts integration build CI job
acts-project/traccc pull request #650
Opened 2024-07-23 11:44 UTC by stephenswat

This commit adds a new CI job that tries to build Acts with the traccc plugin as it exists in the tag for which the CI job is launched. This will help ensure compatibility with Acts until the integration takes place.

2024-07-23 11:46 UTC, stephenswat commented
Pinging @fredevb; check out the change to the CMakeLists.txt file that allows this to compile.

2024-07-23 11:50 UTC, stephenswat commented on .github/workflows/acts_integration.yml
> +            -B build_acts
@fredevb Ideally, the setup would be much simpler so these flags would not be necessary:

```suggestion
            -DCMAKE_BUILD_TYPE=${{ matrix.build }} \
            -DCMAKE_CXX_STANDARD=20 \
            -DCMAKE_CUDA_STANDARD=20 \
            -DCMAKE_HIP_STANDARD=20 \
            -DCMAKE_SYCL_STANDARD=20 \
            -DACTS_BUILD_PLUGIN_TRACCC=ON \
            -DACTS_SETUP_TRACCC=ON \
            -DACTS_TRACCC_SOURCE="SOURCE_DIR;${GITHUB_WORKSPACE}/traccc" \
            -S ${GITHUB_WORKSPACE}/acts \
            -B build_acts
```

2024-09-29 14:51 UTC, paulgessinger commented on .github/workflows/acts_integration.yml
> +          - Debug
Do we need to test both? I imagine they should either both work or both fail, right?

2024-09-29 14:51 UTC, paulgessinger commented on .github/workflows/acts_integration.yml
> +          - main
Do we expect random breakage due to changes in the ACTS repo that would pop up here?

2024-09-30 08:07 UTC, krasznaa requested changes
We should talk about it in person... The setup of this will need to be more complicated than this. I'm on board with this type of a check, but as we know from the similar jobs that we have for Acts and Gaudi (and their integration into Athena), in this simple setup the job would just fail pretty often.

We have mechanisms that we use for Acts and Gaudi to be able to handle interface changes. If we want to introduce a test like this, we'll have to use the same mechanism between Acts and traccc.

2024-10-02 09:05 UTC, closed without merging