Issue warnings for non-Release builds
acts-project/traccc pull request #701
Opened 2024-09-16 09:08 UTC by stephenswat

A common pitfall when using traccc seems to be that people build it in non-Release mode and then get poor performance. This commit adds a bunch of warning prints to make sure that the code will inform you if you try to run it in non-Release mode.

2024-09-16 09:39 UTC, krasznaa commented
So, you pretty much add this printout to every single executable as I can see it. :thinking: Would it not be easier to just print a warning when `traccc::core` is loaded? Then we wouldn't need to remember to put this macro into all the executables. Not to mention that I'm not even that big of a fan of how the macro is set up...

What I'm thinking of is a file called `optimization_warning.cxx` in `core/src`, with something like:

```c++
int checkOptimization() {
#if ...
    std::cerr << ...;
#endif
}
static const int dummy = checkOptimization();
```

It's a bit of a hack, but I've sort of enjoyed how [RooFit](https://root.cern/manual/roofit/) has been printing a greeting message to its users with the same "trick" since forever. :thinking:

2024-09-16 11:08 UTC, stephenswat commented
Updated to affect only the throughput examples.

2024-09-21 16:04 UTC, krasznaa requested changes
Shoot, wanted to make all comments part of the review...

You sure want users to notice these messages. :laughing: 3 printouts per job. :open_mouth: (I'm on board though.)

2024-09-21 16:04 UTC, krasznaa commented on examples/run/common/optimization_warning.hpp
> + * (c) 2022 CERN for the benefit of the ACTS project
```suggestion
 * (c) 2024 CERN for the benefit of the ACTS project
```

2024-09-21 16:05 UTC, krasznaa commented on examples/run/common/optimization_warning.hpp
> +#endif
Coming back to this... Why a macro at this point? A `void optimization_warning()` function would seem perfectly adequate here. The extra function call is not really an issue, it's all happening during the initialization of the throughput applications. :thinking:

2024-09-21 16:05 UTC, krasznaa commented on examples/run/common/optimization_warning.hpp
> +#endif
Okay, I have no idea what the GitHub UI is doing now... :confused:

2024-10-01 06:39 UTC, krasznaa commented
Ping! It would be nice to put this in after some further changes.

2026-05-07 12:31 UTC, closed without merging