Add sanity checks for predicates on vectors
acts-project/traccc pull request #702
Opened 2024-09-18 15:49 UTC by stephenswat

This commit adds four new sanity checks, `true_for_all`, `false_for_all`, `true_for_any`, and `false_for_any` which basically do what they say on the tin.

2024-09-18 16:15 UTC, stephenswat commented on device/sycl/src/sanity/predicate.hpp
> +            return !projection(std::forward<Args>(args)...);
See aforementioned comment.

2024-09-18 16:19 UTC, niermann999 commented on device/sycl/src/sanity/predicate.hpp
> +            return !projection(std::forward<Args>(args)...);
Oh, did not see that this is a device function

2024-09-19 08:18 UTC, stephenswat commented
Feedback incorporated; thanks @niermann999.

2024-09-19 15:31 UTC, beomki-yeo commented
It looks harmless but could you explain the motivation.

2024-09-19 15:33 UTC, stephenswat commented
> It looks harmless but could you explain the motivation.

I want to check whether the volumes in the parameters in the CKF actually make sense, because I am running into a bug where we are navigating through invalid navigation volumes.

2024-09-19 15:40 UTC, beomki-yeo approved these changes
OK. Sounds good

2024-09-22 12:43 UTC, krasznaa requested changes
In general I understand the motivation I believe, but I'm not fond of adding generic code in a project without a concrete use case being there already. I.e. I would prefer seeing these predicates in action as well. Otherwise the design might need to be modified significantly once we actually want to use this code. :thinking:

But more than that, check if you could implement the code such that it would be less AoS specific. See https://github.com/acts-project/traccc/pull/712/commits/28e824715a14ee1b61dbaea3338c9f0636e9b82e, https://github.com/acts-project/traccc/pull/712/commits/7fe10dc397e47cae458f5dbecc7d4462710a032d and https://github.com/acts-project/traccc/pull/712/commits/96416669b485cd515b9e8e3df8b3131610a6fac0 to see what I had to do with the existing code to make it work with SoA containers.

2025-01-21 14:43 UTC, stephenswat commented
Closing as this is no longer as pressing.

2025-01-21 14:43 UTC, closed without merging