ref: benchmark toy detector config
acts-project/traccc pull request #714
Opened 2024-09-24 13:24 UTC by niermann999

Allow the toy detector grids to find all neighboring surfaces, this should increase the number of tracks that can be found and fitted. Furthermore, I restricted the simulation to an eta region, where the tracks should hit a decent number of sensitive surface. Apart from that, the detector is now copied to device instead of using managed memory.

Edit: I also remove the copy of the track states back to host containers and allowed openMP to use dynamic scheduling for better load balancing

2024-10-08 14:28 UTC, niermann999 commented
As soon as I let the grid actually search for neighbouring surfaces, the perfromance gets really bad...
```
Running ./bin/traccc_benchmark_cpu
Run on (48 X 2551.74 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x24)
  L1 Instruction 32 KiB (x24)
  L2 Unified 512 KiB (x24)
  L3 Unified 32768 KiB (x4)
Load Average: 0.92, 0.66, 1.04
WARNING: No entries in volume finder

Detector check: OK
-----------------------------------------------------------------------------------
Benchmark                         Time             CPU   Iterations UserCounters...
-----------------------------------------------------------------------------------
ToyDetectorBenchmark/CPU 1.8804e+10 ns   1.3231e+10 ns            1 event_throughput_Hz=7.55819/s
```
Running ./bin/traccc_benchmark_cuda
Run on (48 X 2270.35 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x24)
  L1 Instruction 32 KiB (x24)
  L2 Unified 512 KiB (x24)
  L3 Unified 32768 KiB (x4)
Load Average: 1.80, 2.18, 1.64
WARNING: No entries in volume finder

Detector check: OK
------------------------------------------------------------------------------------
Benchmark                          Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------
ToyDetectorBenchmark/CUDA 1.3547e+10 ns   1.3471e+10 ns            1 event_throughput_Hz=7.42362/s
```

2025-02-07 13:03 UTC, krasznaa requested changes
You'll think twice about asking for my review on the next PR. 😛

2025-02-07 13:03 UTC, krasznaa commented on io/src/read_detector.cpp
> +template <typename detector_t, unsigned int CAP = 0u>
I expected that the PR would already be making use of this. 🤔

Unfortunately this is a pretty inconvenient API. 😦 Normally you don't need to explicitly define the `detector_t` type, as the compiler can deduce it from your call. But now, if you want to override the second value, you need to define `detector_t` explicitly as well. 😦

Not to mention that this is sitting in the `.cpp` file. Users will not be able to call this thing anyway.

So in this PR, it would be better to not introduce a new template parameter to this helper function, but just to hardcode the `0u` value on line 41. 🤔

2025-02-07 13:03 UTC, krasznaa commented on benchmarks/cuda/toy_detector_cuda.cpp
> +    auto det_fixed_buff = detray::get_buffer(det, device_mr, copy);
Not sure why it's `det_fixed_buff`. I kept looking for what you "fixed" in it. 🤔 Just using `det_buff` would be a bit better of a name I think.

2025-02-07 13:05 UTC, niermann999 commented on benchmarks/cuda/toy_detector_cuda.cpp
> +    auto det_fixed_buff = detray::get_buffer(det, device_mr, copy);
I think I just copied that from somewhere where it meant "fixed size buffer". I will rename it

2025-02-07 13:30 UTC, niermann999 commented on benchmarks/common/benchmarks/toy_detector_benchmark.hpp
> +    }
Indeed

2025-02-07 13:41 UTC, krasznaa approved these changes
Looks technically correct.

2025-02-07 14:49 UTC, merged

2025-02-14 07:42 UTC, beomki-yeo commented
This PR seems to stop the continuous benchmark.