Update detray to v0.80.0
acts-project/traccc pull request #750
Opened 2024-10-24 12:26 UTC by stephenswat

Brings changes to the stepper states and the wire chambers.

2024-10-24 12:51 UTC, niermann999 requested changes

2024-10-24 12:51 UTC, niermann999 commented on core/include/traccc/finding/actors/ckf_aborter.hpp
> +            stepping.step_size() > abrt_state.min_step_length) {
```suggestion
            stepping.path_from_surface() > abrt_state.min_step_length) {
```

2024-10-24 13:21 UTC, stephenswat commented on core/include/traccc/finding/actors/ckf_aborter.hpp
> +            stepping.step_size() > abrt_state.min_step_length) {
Fixed, thanks!

2024-10-24 14:04 UTC, niermann999 approved these changes

2024-10-24 14:08 UTC, krasznaa approved these changes
Sure, all looks reasonable. 🤔

2024-10-24 17:25 UTC, stephenswat commented
I'm getting a bit tired of the OneAPI compiler running into some internal error every other week... :frowning_face:

2024-10-31 12:42 UTC, stephenswat commented
Turns out that the current version of detray, 0.81.0, manages to resolve the compiler bug.

2024-10-31 15:22 UTC, niermann999 approved these changes

2024-10-31 15:50 UTC, merged