CI build for CUDA
acts-project/traccc pull request #78
Opened 2021-08-20 01:42 UTC by beomki-yeo

This adds `-DTRACCC_BUILD_CUDA` option to CI build for cuda

2021-09-01 18:59 UTC, beomki-yeo commented
@paulgessinger do you have any comment on updating docker for recent cuda version?

2021-09-02 07:13 UTC, paulgessinger commented
Hey @beomki-yeo, I hadn't seen this, sorry. I'll have a look today at adding a more recent ubuntu+cuda image.

2021-09-02 12:06 UTC, beomki-yeo commented
Okay. I remember that cuda 11.4 also doesn't work for the seed finding, which I have to debug later (11.0 - 11.3 was fine as far as I remember)

2021-09-02 20:36 UTC, beomki-yeo commented
Hmm Still doesn't work after updating the docker image.

```
/__w/traccc/traccc/build/_deps/vecmem-src/core/include/vecmem/memory/memory_resource.hpp(21): error: name followed by "::" must be a class or namespace name

/__w/traccc/traccc/build/_deps/vecmem-src/core/include/vecmem/memory/polymorphic_allocator.hpp(22): error: name followed by "::" must be a class or namespace name

/__w/traccc/traccc/build/_deps/vecmem-src/core/include/vecmem/memory/polymorphic_allocator.hpp(22): error: expected a ";"
```

When I follow [memory_resource.hpp](https://github.com/acts-project/vecmem/blob/main/core/include/vecmem/memory/memory_resource.hpp),  the compiler is pointed to `experimental/memory_resource` rather than `memory_resource`. Anyone has an idea why it happens? @paulgessinger @krasznaa @stephenswat

2021-09-03 00:38 UTC, beomki-yeo commented
When I tested with my laptop (centos8, gcc 9.2 and cuda 11.3), the compilation was OK.

2021-09-03 07:23 UTC, paulgessinger commented
That's odd. I thought the `__has_include` macros would give an explicit error if that header was not found. It seems to include something, but then it's not in the correct namespace, or similar. This might be a difference in the standard libraries between C8 and Ubuntu?

2021-09-06 08:32 UTC, stephenswat commented
I have a fix for this behaviour which I will open a PR for on vecmem in just a moment.

2021-09-06 09:06 UTC, stephenswat commented
I think that, for a more solid solution, we will need to ensure that both the host-host compiler, the NVIDIA host compiler, and the NVIDIA CUDA compiler, have their C++ version set to the minimum version required for each of those three parts. In this particular case that would mean either using C++14 for the entire traccc project, or moving to C++17 for the NVIDIA compiler.

2021-09-06 10:49 UTC, stephenswat commented
The CI issues should be resolved with the introduction of #83. Rerunning the jobs to make sure that that is the case.

2021-09-06 13:18 UTC, krasznaa commented
While Stephen is still debugging the build on his own machine, at least the failure in the CI is understood. It turns out that CMake 3.17, which is in the Docker image, does not support C\+\+17 for CUDA yet.

https://gitlab.kitware.com/cmake/cmake/-/blob/v3.17.5/Modules/Compiler/NVIDIA-CUDA.cmake

So... @paulgessinger... we'd need a newer version of CMake in that Docker image. Let's just go for the current very latest one, 3.21.2, for some future-proofing.

2021-09-06 13:27 UTC, paulgessinger commented
I see, we could bump this I just used what we have for the other images. I'll be off for a bit, so I won't get around to do it very soon. You can open PR to the machines repo, and I can move that along.

2021-09-06 16:30 UTC, stephenswat commented
> I thought the same thing but it doesn't resolve the issue (...) Possibly CMake version or vecmem itself is the reason as mentioned above

Yeah work is in progress, it turned out to be a big of a deeper problem than I initially thought. Hope to have it fixed by tonight!

2021-09-07 23:57 UTC, beomki-yeo commented
@krasznaa @stephenswat can you make a new version tag for vecmem?

2021-09-08 12:48 UTC, krasznaa commented
> @krasznaa @stephenswat can you make a new version tag for vecmem?

Unfortunately the changes that we made in vecmem recently will not help with your use case. I'll make a new tag today, but I don't think that will help you in any way. Since the header that you ended up including in your `.cu` file, must be processed in C\+\+17 mode. This may or may not work with NVCC. Generally, "device compilers" are not meant to see that header at all...

2021-09-08 13:02 UTC, krasznaa commented
Here it is: https://github.com/acts-project/vecmem/releases/tag/v0.3.0

I'll open a PR for updating traccc to that version, after some further tests...

2021-09-08 13:06 UTC, stephenswat commented
Good news! The new CI images have been built and uploaded. Let's retry the CI on this one.

2021-09-08 13:50 UTC, stephenswat commented
It seems like Github Actions is out to frustrate me this week. Turns out the container registry has not (yet?) registered the new version as the new `latest` build: https://github.com/acts-project/machines/pkgs/container/ubuntu2004_cuda

2021-09-08 19:58 UTC, beomki-yeo commented
Okay now it works. thanks guys

2021-09-10 09:49 UTC, stephenswat requested changes
Looks good overall, just have a few questions. Once those are resolved I am happy to merge.

2021-09-10 09:49 UTC, stephenswat commented on .github/workflows/builds.yml
> +      - uses: actions/checkout@v1
Is there a reason to downgrade this step to version 1? Does v2 not do what we need it to do?

2021-09-10 09:49 UTC, stephenswat commented on .github/workflows/builds.yml
> +        run: >
I don't think it is ideal to do this with bash scripting, but for now it's fine as it is. Let's think of a more robust way to do this at a later point.

2021-09-10 09:49 UTC, stephenswat commented on .github/workflows/builds.yml
> +              -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc \
I would recommend `$(which nvcc)` here to make the finding a little more robust if we add more platforms later.

2021-09-10 09:49 UTC, stephenswat commented on .github/workflows/builds.yml
> +        run: CTEST_PARALLEL_LEVEL=$(nproc) cmake --build build -- test
Minor thing, but can we get the EOF newline back?

2021-09-10 17:15 UTC, stephenswat approved these changes

2021-09-13 19:52 UTC, stephenswat approved these changes

2021-09-13 20:19 UTC, merged